# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProblemSolutionInfra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
