# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProblemSolutionInfra', '0002_problem_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
                ('data', models.FileField(upload_to='solutions/%Y/%m/%d/')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProblemSolutionInfra.Problem')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
