# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataInventoryMgmt', '0003_dataset_downloads_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='downloads_count',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
